---
#----------------------------------------------------------------------------------------------
# This is the report configuration file of the report builder app
# Please note: when changing values here, you need to check whether specific choice indexes
#             are used within Server.R
#----------------------------------------------------------------------------------------------

#----------------------------------------------------------
# Main view choices and text of the report builder
#----------------------------------------------------------
#Report type choices at the top
report_template_choices:
  - "AllHaemV1_AH(56)" : "AH"
    "AllHaemV1_AH(56)_cfDNA" : "AH_cfDNA"
    "AllHaemV1_AHD(57)" : "AHD"
    "AllHaemV1_AHD(57)_DDX41" : "AHD_DDX41"
    "AllHaemV1_MDX(22)" : "MDX"
    "AllHaemV1_MDX(22)_MPNcontext" : "MDX_MPN"
    "AllHaemV1_SG(TP53)" : "SG_TP53"
    "AllHaemV1_SG(TP53)_CLLcontext" : "SG_TP53_CLL"
report_type_choices:
  - "VARIANTS DETECTED" : "VAR"
    "NO VARIANTS DETECTED" : "NEG"
    "FAILED" : "FAIL"
#Speciman type choices which will appear in the header section of the report with sample and patient details
specimen_type_choices:
  - "Bone marrow aspirate" : "bone marrow aspirate "
    "Bone marrow aspirate (CD19 selected)" : "bone marrow aspirate "
    "Bone marrow aspirate (gDNA received)" : "bone marrow aspirate "
    "Bone marrow trephine biopsy" : "bone marrow trephine biopsy "
    "Bone marrow trephine biopsy (gDNA received)" : "bone marrow trephine biopsy "
    "Buccal swab" : "buccal swab "
    "Cell free DNA (cfDNA)" : "cfDNA "
    "Cells" : "cells "
    "Cells (gDNA received)" : "cells "
    "Cerebrospinal fluid" : "fluid "
    "Fluid" : "fluid "
    "Hair follicle" : "hair follicle "
    "Hair follicle (gDNA received)" : "hair follicle "
    "Peripheral blood" : "peripheral blood "
    "Peripheral blood (CD19 selected)" : "peripheral blood "
    "Peripheral blood (gDNA received)" : "peripheral blood "
    "Pleural fluid" : "fluid "
    "Saliva" : "saliva "
    "Tissue (FFPE)" : "tissue "
    "Tissue (FFPE) (gDNA received)" : "tissue "
    "Tissue (fresh)" : "tissue "
    "Tissue (fresh) (gDNA received)" : "tissue "

#Clinical context, not moved to the clinical context mapping csv file because there can be ones not linked to a header
clinical_context_choices:
  - "Acquired Aplastic Anaemia and Hypoplastic mds"
  - "Acute Leukaemias of Ambiguous Lineage"
  - "Acute Myeloid Leukaemia"
  - "AML in Morphological Remission"
  - "AML with mutated CEBPA"
  - "AML with Mutated NPM1"
  - "B-Lymphoblastic Leukaemia or Lymphoma"
  - "Chronic Lymphocytic Leukaemia or Small Lymphocytic Lymphoma"
  - "Chronic Myeloid Leukaemia"
  - "Classical Myeloproliferative Neoplasms"
  - "Clonal Haematopoiesis"
  - "Core Binding Factor Acute Myeloid Leukaemia"
  - "Follicular Lymphoma"
  - "High Grage B-Cell Lymphoma"
  - "Investigation of Cytopenias"
  - "Investigation of Eosinophilia"
  - "Investigation of Possible T-Cell Lymphoma"
  - "Low Grade B-Cell Lymphomas"
  - "Malignant Histiocytoses"
  - "Mantle Cell Lymphoma"
  - "Mature T- and NK-Cell Lymphoma"
  - "Myelodysplastic or Myeloproliferative Neoplasms"
  - "Myelodysplastic Syndrome"
  - "Myeloid Neoplasms Post Cytotoxic Therapy"
  - "Myeloid Neoplasms with Germline DDX41 Mutation"
  - "Myeloid Proliferations Associated with Down Syndrome"
  - "Plasma Cell Myeloma"
  - "Somatic Mutation Testing in Germline Disease"
  - "Systemic Mastocytosis"
  - "T-Lymphoblastic Leukaemia or Lymphoma"
assumed_origin_choices:
  - "Somatic"
  - "Somatic (consider excluding germline)"
  - "Somatic (recommend excluding germline)"
  - "Donor cell derived"
  - "Uncertain"
  - "Germline"
assumed_origin_somatic:
  - "Somatic"
  - "Somatic (consider excluding germline)"
  - "Somatic (recommend excluding germline)"
variant_table_add:
  - "FLT3" : "FLT3-ITD (allelic ratio [xxx])"
  - "BCL2" : "Aberrant Somatic Hypermutation"
clinical_significance_choices:
  - "CLONAL MARKER"
  - "CLONAL MARKER - consider lymphoid origin"
  - "CLONAL MARKER - consider myeloid origin"
  - "DIAGNOSTIC"
  - "DRUG TARGET"
  - "DRUG RESISTANCE"
  - "PROGNOSTIC"
  - "DIAGNOSTIC / PROGNOSTIC"
  - "DIAGNOSTIC / PROGNOSTIC / MRD MARKER"
  - "DIAGNOSTIC / DRUG TARGET"
  - "PROGNOSTIC / DRUG TARGET"
  - "DIAGNOSTIC / PROGNOSTIC / DRUG TARGET"
  - "UNKNOWN - atypical variant type"
  - "Unknown - consider testing a germline sample to determine origin"
  - "Likely none"
  - "PREDISPOSITION - if confirmed germline. See below"
  - "UNCERTAIN - if confirmed germline. See below"
  - "See comment above"
clinical_significance_mapping:
- "00000" : "CLONAL MARKER"
  "10000" : "DIAGNOSTIC"
  "00100" : "DRUG TARGET"
  "00010" : "DRUG RESISTANCE"
  "01000" : "PROGNOSTIC"
  "11000" : "DIAGNOSTIC / PROGNOSTIC"
  "11001" : "DIAGNOSTIC / PROGNOSTIC / MRD MARKER"
  "10100" : "DIAGNOSTIC / DRUG TARGET"
  "01100" : "PROGNOSTIC / DRUG TARGET"
  "11100" : "DIAGNOSTIC / PROGNOSTIC / DRUG TARGET"
origin_vs_clinical_significance:
  - "Uncertain" : "Unknown - consider testing a germline sample to determine origin"
    "Germline" : "Likely none"
    "Donor cell derived" : " "
correlative_morphology_text: "(refer to [Laboratory name] report, Lab ID [XXX])"
specimen_details_text: "(Record block ID here if applicable)"

# Results summary
results_summary_neg: "NO VARIANTS DETECTED. "
results_summary_var: "See Reportable Variants table below for details. "
results_summary_fail: "Failed assay due to suboptimal DNA quantity/quality."
results_symmary_fail_cfdna: "Failed assay due to suboptimal DNA quantity/quality. See comment below regarding the test limitations of cell free DNA analysis."
results_summary_flt3:
  - "Please note, a separate FLT3-ITD assay has not been performed. "
  - "Additionally, FLT3-ITD was NOT DETECTED by a separate assay. "
results_summary_qual:
  - "Please note that the DNA quantity/quality for this sample was suboptimal, as a result the sensitivity of this assay is reduced. "
  - "The low tumour burden in this sample is noted. Recommend repeat testing if possible on sample with higher tumour burden. "
  - "Please note that the tumour burden in this sample is low and the DNA quantity/quality was suboptimal. As a result the sensitivity of this assay is reduced. Consider repeat testing of a sample with a higher tumour burden. "
results_summary_variants_detected:
  - "ASSUMED SOMATIC VARIANT DETECTED. "
  - "ASSUMED SOMATIC VARIANTS DETECTED. "
  - "NO ASSUMED SOMATIC VARIANTS DETECTED. "
  - "VARIANT OF UNCERTAIN ORIGIN DETECTED. "
  - "ASSUMED GERMLINE DDX41 VARIANT DETECTED. "
  - "ASSUMED SOMATIC VARIANTS AND ASSUMED GERMLINE DDX41 VARIANT DETECTED. "
  - "GERMLINE DDX41 VARIANT DETECTED.  NO ASSUMED SOMATIC VARIANTS DETECTED. "

#FLT3_ITD
flt3_itd_assay:
- "SEPARATE FLT3-ITD ASSAY NOT PERFORMED "
- "FLT3-ITD NOT DETECTED BY SEPARATE ASSAY "
- "FLT3-ITD DETECTED BY SEPARATE ASSAY (see Reportable Variants table for details) "

ddx41_vartype_choices:
  - "Somatic Variants Plus DDX41 C4/5 Variant" : "VAR_DDX41_C45"
    "Somatic Variants Plus DDX41 C3 Variant" : "VAR_DDX41_C3"
    "DDX41 C4/5 Variant Only" : "DDX41_C45"
    "DDX41 C3 Variant Only" : "DDX41_C3"
    "DDX41 Monitoring" : "MONITORING"
    "None" : "NONE"

# Clinical interpretation
clinical_interpretation: "Refer to final page of report for further information regarding the clinical utility of genomic testing in this context."
clinical_interpretation_CEBPA: "The CEBPA variant/s detected in a previous **** sample from this patient (lab ID ****, collected dd-mmm-yyyy) was/were not detected in this hair sample. This result is consistent with a somatic (non-germline) origin of the originally observed CEBPA variant/s. "
clinical_interpretation_select:
  - "Please correlate with morphological, immunophenotypic and cytogenetic features. "
  - "Please correlate with histological features. "
clinical_interpretation_var:
  - "A [XXX] variant was "
  - "Variants in [XXX] were "
  - "An assumed somatic [XXX] variant was "
  - "Assumed somatic variants in [XXX] were "
  - "A variant of likely germline origin and of likely no clinical significance was "
  - "Variants of likely germline origin and of likely no clinical significance were "
  - "A variant of uncertain origin (i.e. somatic versus germline) was "
  - "Variants of uncertain origin (i.e. somatic versus germline) were "

clinical_interpretation_disease:
  - "acute myeloid leukaemia (AML)"
  - "acute myeloid leukaemia (AML) with mutated CEBPA"
  - "acute myeloid leukaemia (AML) with inv(16)/t(16;16)"
  - "acute myeloid leukaemia (AML) with mutated NPM1"
  - "acute myeloid leukaemia (AML) with t(8;21)"
  - "angioimmunoblastic T-cell lymphoma (AITL)"
  - "aplastic anaemia"
  - "atypical chronic myeloid leukaemia (aCML)"
  - "B-lymphoblastic leukaemia (B-ALL)"
  - "a B-cell lymphoproliferative disorder (B-LPD)"
  - "blastic plasmacytoid dendritic cell neoplasm (BPDCN)"
  - "breast implant-associated anaplastic large cell lymphoma (BIA-ALCL)"
  - "chronic lymphocytic leukaemia (CLL)"
  - "chronic myeloid leukaemia (CML)"
  - "chronic myelomonocytic leukaemia (CMML)"
  - "***the presence of clonal haematopoiesis"
  - "diffuse large B-cell lymphoma (DLBCL)"
  - "follicular lymphoma"
  - "hairy cell leukaemia (HCL)"
  - "Hodgkin lymphoma"
  - "juvenile myelomonocytic leukaemia (JMML)"
  - "Langerhans cell histiocytosis (LCH)"
  - "mantle cell lymphoma (MCL)"
  - "marginal zone lymphoma "
  - "myelodysplastic syndrome (MDS)"
  - "myelodysplastic syndrome with excess blasts (MDS-EB)"
  - "myelodysplastic syndrome with single lineage dysplasia (MDS-SLD)"
  - "myelodysplastic syndrome with multilineage dysplasia (MDS-MLD)"
  - "myelodysplastic syndrome with ring sideroblasts (MDS-RS)"
  - "myelodysplastic syndrome with ring sideroblasts and single lineage dysplasia (MDS-RS-SLD)"
  - "myelodysplastic syndrome with ring sideroblasts and multilineage dysplasia (MDS-RS-MLD)"
  - "a myelodysplastic/myeloproliferative neoplasm"
  - "myelodysplastic/myeloproliferative neoplasm, unclassifiable (MDS/MPN-U)"
  - "myelodysplastic/myeloproliferative neoplasm with ring sideroblasts and thrombocytosis (MDS/MPN-RS-T)"
  - "a myeloid neoplasm post cytotoxic therapy (MN-pCT)"
  - "a myeloproliferative neoplasm (MPN)"
  - "myeloid sarcoma"
  - "peripheral T-cell lymphoma (PTCL)"
  - "plasma cell myeloma (PCM)"
  - "primary mediastinal large B-cell lymphoma (PMLBCL)"
  - "systemic mastocytosis"
  - "systemic mastocytosis with an associated haematological neoplasm (SM-AHN)"
  - "a T-cell lymphoproliferative disorder (T-LPD)"
  - "T-lymphoblastic leukaemia (T-ALL)"
  - "T-cell prolymphocytic leukaemia (T-PLL)"
  - "Waldenstr√∂m macroglobulinaemia (WM)"
clinical_interpretation_ddx41:
  - "A pathogenic "
  - "A likely pathogenic "
clinical_interpretation_var_text1: "detected in this "
clinical_interpretation_var_text2: "sample consistent with a diagnosis of "
ddx41_pathogenicity:
  - "Pathogenic (class 5) in "
  - "Likely Pathogenic (class 4) in "
  - "a variant of uncertain significance (class 3) in the setting of "
  - "Likely Benign (class 2) in "
  - "Benign (class 1) in "
report_status:
  - "First Complete"
  - "Second Complete"
  - "Final"
ddx41_variant_analysis1: "A heterozygous [VARIANT TYPE/DETAIL] variant was detected in DDX41. [EVIDENCE SENTENCES]. Based on current evidence, this variant is considered "
ddx41_variant_analysis2: "the autosomal dominant condition Myeloproliferative/lymphoproliferative neoplasms, familial (multiple types), susceptibility (OMIM 616871) and in the setting of a myeloid neoplasm may be diagnostic of a myeloid neoplasm with germline DDX41 mutation (WHO 2017). Please note, this result should be confirmed in a non-haematological specimen."
ddx41_monitoring_text: "This germline DDX41 variant was detected in a previous ***** sample from this patient (lab ID ********, collected **-***-20**). No assumed somatic variants in DDX41 were detected."
ddx41_c3_text1: "A variant of uncertain significance assumed to be of germline origin was detected in DDX41 in this "
ddx41_c3_text2: "sample. Further testing is required to confirm a germline origin of this variant. If confirmed germline, consider segregation of this variant in this family to further clarify its significance as well as testing for this variant in any potential familial stem cell donors. Consider referral to a genetics service depending on clinical context."
ddx41_c45_text1: "variant assumed to be of germline origin was detected in DDX41 in this "
ddx41_c45_text2: "sample. Further testing is required to confirm a germline origin of this variant. If confirmed germline, this result is consistent with a familial susceptibility to myeloid neoplasms in this patient. This result has potential diagnostic and clinical management implications for both the patient and other at-risk family members and referral to a genetics service is recommended. In addition, testing for this variant in any possible familial stem cell donors is strongly recommended."
var_ddx41_C3_text: "In addition, a variant of uncertain significance assumed to be of germline origin was detected in DDX41. Further testing is required to confirm a germline origin of this variant. If confirmed germline, consider segregation of this variant in this family to further clarify its significance as well as testing for this variant in any potential familial stem cell donors. Consider referral to a genetics service depending on clinical context."
var_ddx41_c45_text1: "sample consistent with a myeloid neoplasm arising in the context of suspected germline DDX41 disease. \n\nIn addition, "
var_ddx41_c45_text2: "variant assumed to be of germline origin was detected in DDX41. Further testing is required to confirm a germline origin of this variant. If confirmed germline, this result is consistent with a familial susceptibility to myeloid neoplasms in this patient. This result has potential diagnostic and clinical management implications for both the patient and other at-risk family members and referral to a genetics service is recommended. In addition, testing for this variant in any possible familial stem cell donors is strongly recommended."
authorised_by: "A/Prof Piers Blombery (Consultant Haematologist)"
specimen_na: "N/A"
correlative_morphology_na: "N/A"
correlative_morphology_np: "Not provided"
clinical_interpretation_var_default: "Please select from above drop downs "
flt3_Itd_var: "FLT3-ITD (allelic ratio [XXX])"
bcl2_var: "Aberrant Somatic Hypermutation"
vrf_na: "N/A"

#----------------------------------------------------------
# Modal dialog choices, for misc clinical indication text
#----------------------------------------------------------
misc_category_prognosis:
  - "This molecular profile is associated with inferior outcomes."
  - "This molecular profile is associated with inferior outcomes according to ELN 2022 criteria."
  - "This molecular profile is associated with intermediate outcomes according to ELN 2022 criteria."
  - "In the absence of adverse risk cytogenetics, this molecular profile is associated with intermediate outcomes according to ELN 2022 criteria."
  - "This molecular profile is associated with favourable outcomes."
  - "This molecular profile is associated with favourable outcomes according to ELN 2022 criteria."
  - "This molecular profile is associated with favourable outcomes according to ELN 2022 criteria, however the complex molecular profile is noted."
  - "In the absence of adverse risk cytogenetics, this molecular profile is associated with favourable outcomes according to ELN 2022 criteria."
misc_previous_variants:
  - "This variant was detected in a previous **** sample from this patient (lab ID ***, collected***)."
  - "These variants were detected in a previous **** sample from this patient (lab ID ***, collected***)."
  - "The [gene] [variant] variant/s was/were detected in a previous **** sample from this patient (lab ID ***, collected***) whereas the [gene] [variant] variant/s was/were not previously detected."
  - "This variant was not detected in a previous **** sample from this patient (lab ID ***, collected***)."
  - "These variants were not detected in a previous **** sample from this patient (lab ID ***, collected***)."
  - "The [gene] [variant] variant was not targeted by the previously performed assay."
  - "The [genes] [variants] variants were not targeted by the previously performed assay."
misc_variants_assumed_germline:
  - "Testing of a germline sample (e.g. hair) to exclude a germline origin of the [gene] [variant] variant is recommended."
misc_disease_comments:
  - "[Gene] variants are frequently observed in clonal haematopoiesis of indeterminate potential and across the spectrum of myeloid neoplasms."
  - "[Gene] variants are frequently observed in clonal haematopoiesis of indeterminate potential and across the spectrum of myeloid neoplasms including myelodysplastic syndromes, myeloproliferative neoplasms, myelodysplastic/myeloproliferative overlap neoplasms and acute myeloid leukaemia."
  - "The persistence of this variant in the absence of overt leukaemia in this sample may represent low level residual disease or alternatively the presence of a preleukaemic clone."
  - "The persistence of these variants in the absence of overt leukaemia in this sample may represent low level residual disease or alternatively the presence of a preleukaemic clone."
  - "No typical MPN driver variants (JAK2/CALR/MPL) were detected in this sample."
  - "SF3B1 variants are morphologically associated with the presence of ring sideroblasts."
misc_coexisting_haem_malignancies:
  - "The haematological compartment (myeloid vs lymphoid) from which the [gene] [variant] variant has arisen cannot be determined by this assay."
  - "The haematological compartment (myeloid vs lymphoid) from which the [genes] [variants] variants have arisen cannot be determined by this assay."
misc_vaf_comments:
  - "The TP53 variant was detected at a variant read frequency consistent with an acquired loss of heterozygosity at this locus."
  - "The JAK2 Val617Phe variant was detected at a variant read frequency consistent with an acquired loss of heterozygosity at this locus."
  - "Please note that the sensitivity of this assay is approximately 2% which in the clinical context of Systemic Mastocytosis (SM) is not adequate to fully exclude the presence of a KIT Asp816Val variant (as they are frequently present at very low level). Further testing with a more sensitive assay for the KIT Asp816Val variant should be considered in this patient (not performed by this laboratory)."
  - "Please note a more sensitive allele specific assay for the [e.g. MYD88 Leu265Pro] variant ****is being/has been**** performed on this sample - refer to separate report."
misc_other_tests_performed:
  - "An NPM1 measurable residual disease assay has been performed on this sample - refer to separate report."
  - "An Inherited Bone Marrow Disorders NGS panel has been performed on this sample - refer to separate report."
  - "A PanHaem Tumour NGS panel has been performed on this sample - refer to separate report."
  - "A UBA1 gene variant analysis has also been performed on this sample - refer to separate report."


